<Project>
    <PropertyGroup>
        <TargetFrameworkVersion>net10.0</TargetFrameworkVersion>
        <AnalysisMode>All</AnalysisMode>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <NoWarn>$(NoWarn);CA1303;CA1848;CA5394</NoWarn>
    </PropertyGroup>
</Project>